/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Testing;

/**
 *
 * @author denisehfg
 */
public class GUI_Test extends javax.swing.JFrame {

    /**
     * Creates new form GUI_Test
     */
    public GUI_Test() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Main_Screen = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Programmieren_Screen1 = new javax.swing.JPanel();
        jButton29 = new javax.swing.JButton();
        jButton30 = new javax.swing.JButton();
        jButton31 = new javax.swing.JButton();
        jButton32 = new javax.swing.JButton();
        jButton33 = new javax.swing.JButton();
        jButton34 = new javax.swing.JButton();
        jButton35 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        Basics_Screen2 = new javax.swing.JPanel();
        jButton52 = new javax.swing.JButton();
        jButton53 = new javax.swing.JButton();
        jButton54 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        Mathe_Screen4 = new javax.swing.JPanel();
        jButton87 = new javax.swing.JButton();
        jButton88 = new javax.swing.JButton();
        jButton89 = new javax.swing.JButton();
        jButton90 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Main_Screen.setBackground(new java.awt.Color(255, 255, 255));
        Main_Screen.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Circle_Info.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.setBorder(null);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Circle_Prog.png"))); // NOI18N
        jButton2.setBorder(null);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Circle_Typo.png"))); // NOI18N
        jButton4.setBorder(null);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Circle_Mathe.png"))); // NOI18N
        jButton3.setBorder(null);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Circle_Basics.png"))); // NOI18N
        jButton5.setBorder(null);

        javax.swing.GroupLayout Main_ScreenLayout = new javax.swing.GroupLayout(Main_Screen);
        Main_Screen.setLayout(Main_ScreenLayout);
        Main_ScreenLayout.setHorizontalGroup(
            Main_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_ScreenLayout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addGroup(Main_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Main_ScreenLayout.createSequentialGroup()
                        .addGroup(Main_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Main_ScreenLayout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(154, 154, 154)
                                .addComponent(jButton5))
                            .addGroup(Main_ScreenLayout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(154, 154, 154)
                                .addComponent(jButton2)))
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Main_ScreenLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(270, 270, 270))))
        );
        Main_ScreenLayout.setVerticalGroup(
            Main_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_ScreenLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(Main_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Main_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Main_Screen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Main_Screen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2516, 2516, 2516))
        );

        Programmieren_Screen1.setBackground(new java.awt.Color(255, 255, 255));
        Programmieren_Screen1.setForeground(new java.awt.Color(255, 255, 255));

        jButton29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Circle_Prog.png"))); // NOI18N
        jButton29.setBorder(null);

        jButton30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Programmieren/Circle_Klassendef.png"))); // NOI18N
        jButton30.setBorder(null);

        jButton31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Programmieren/Circle_Array.png"))); // NOI18N
        jButton31.setBorder(null);

        jButton32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Programmieren/Circle_ObjundKla.png"))); // NOI18N
        jButton32.setBorder(null);

        jButton33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Programmieren/Circle_Schleifen.png"))); // NOI18N
        jButton33.setBorder(null);

        jButton34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Programmieren/Circle_if.png"))); // NOI18N
        jButton34.setBorder(null);

        jButton35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Programmieren/Circle_Schleifen.png"))); // NOI18N
        jButton35.setBorder(null);

        javax.swing.GroupLayout Programmieren_Screen1Layout = new javax.swing.GroupLayout(Programmieren_Screen1);
        Programmieren_Screen1.setLayout(Programmieren_Screen1Layout);
        Programmieren_Screen1Layout.setHorizontalGroup(
            Programmieren_Screen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Programmieren_Screen1Layout.createSequentialGroup()
                .addGroup(Programmieren_Screen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Programmieren_Screen1Layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jButton32)
                        .addGap(18, 18, 18)
                        .addGroup(Programmieren_Screen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton29)
                            .addComponent(jButton34))
                        .addGap(30, 30, 30)
                        .addComponent(jButton35))
                    .addGroup(Programmieren_Screen1Layout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addGroup(Programmieren_Screen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton33, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Programmieren_Screen1Layout.createSequentialGroup()
                                .addComponent(jButton31)
                                .addGap(115, 115, 115)
                                .addComponent(jButton30)
                                .addGap(219, 219, 219)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Programmieren_Screen1Layout.setVerticalGroup(
            Programmieren_Screen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Programmieren_Screen1Layout.createSequentialGroup()
                .addGroup(Programmieren_Screen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Programmieren_Screen1Layout.createSequentialGroup()
                        .addGroup(Programmieren_Screen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Programmieren_Screen1Layout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jButton31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Programmieren_Screen1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton30)))
                        .addGroup(Programmieren_Screen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Programmieren_Screen1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton29)
                                .addGap(29, 29, 29)
                                .addComponent(jButton34))
                            .addGroup(Programmieren_Screen1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jButton32)))
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Programmieren_Screen1Layout.createSequentialGroup()
                        .addComponent(jButton35)
                        .addGap(197, 197, 197)))
                .addComponent(jButton33)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(Programmieren_Screen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(481, 481, 481)
                .addComponent(Programmieren_Screen1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1761, 1761, 1761))
        );

        Basics_Screen2.setBackground(new java.awt.Color(255, 255, 255));
        Basics_Screen2.setForeground(new java.awt.Color(255, 255, 255));

        jButton52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Circle_Basics.png"))); // NOI18N
        jButton52.setBorder(null);

        jButton53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Basics/Circle_Bruchrechnen.png"))); // NOI18N
        jButton53.setBorder(null);

        jButton54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Basics/Circle_Dreiecke.png"))); // NOI18N
        jButton54.setBorder(null);

        javax.swing.GroupLayout Basics_Screen2Layout = new javax.swing.GroupLayout(Basics_Screen2);
        Basics_Screen2.setLayout(Basics_Screen2Layout);
        Basics_Screen2Layout.setHorizontalGroup(
            Basics_Screen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Basics_Screen2Layout.createSequentialGroup()
                .addContainerGap(254, Short.MAX_VALUE)
                .addGroup(Basics_Screen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Basics_Screen2Layout.createSequentialGroup()
                        .addComponent(jButton54)
                        .addGap(115, 115, 115)
                        .addComponent(jButton53)
                        .addGap(219, 219, 219))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Basics_Screen2Layout.createSequentialGroup()
                        .addComponent(jButton52)
                        .addGap(325, 325, 325))))
        );
        Basics_Screen2Layout.setVerticalGroup(
            Basics_Screen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Basics_Screen2Layout.createSequentialGroup()
                .addGroup(Basics_Screen2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Basics_Screen2Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButton54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Basics_Screen2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton53)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton52)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(Basics_Screen2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(1236, 1236, 1236)
                .addComponent(Basics_Screen2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(1176, 1176, 1176))
        );

        Mathe_Screen4.setBackground(new java.awt.Color(255, 255, 255));
        Mathe_Screen4.setForeground(new java.awt.Color(255, 255, 255));

        jButton87.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Circle_Mathe.png"))); // NOI18N
        jButton87.setBorder(null);

        jButton88.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Basics/Circle_Dreiecke.png"))); // NOI18N
        jButton88.setBorder(null);

        jButton89.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Mathe/Circle_Komplexe.png"))); // NOI18N
        jButton89.setBorder(null);

        jButton90.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Mathe/Circle_Grundbegriffe.png"))); // NOI18N
        jButton90.setBorder(null);

        javax.swing.GroupLayout Mathe_Screen4Layout = new javax.swing.GroupLayout(Mathe_Screen4);
        Mathe_Screen4.setLayout(Mathe_Screen4Layout);
        Mathe_Screen4Layout.setHorizontalGroup(
            Mathe_Screen4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Mathe_Screen4Layout.createSequentialGroup()
                .addContainerGap(254, Short.MAX_VALUE)
                .addGroup(Mathe_Screen4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Mathe_Screen4Layout.createSequentialGroup()
                        .addComponent(jButton87)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton90))
                    .addGroup(Mathe_Screen4Layout.createSequentialGroup()
                        .addComponent(jButton89)
                        .addGap(115, 115, 115)
                        .addComponent(jButton88)))
                .addGap(219, 219, 219))
        );
        Mathe_Screen4Layout.setVerticalGroup(
            Mathe_Screen4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Mathe_Screen4Layout.createSequentialGroup()
                .addGroup(Mathe_Screen4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Mathe_Screen4Layout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButton89))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Mathe_Screen4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton88)))
                .addGroup(Mathe_Screen4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Mathe_Screen4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton87)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Mathe_Screen4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(jButton90)
                        .addGap(95, 95, 95))))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(Mathe_Screen4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(1821, 1821, 1821)
                .addComponent(Mathe_Screen4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(591, 591, 591))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 816, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 14955, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2991, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_Test().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Basics_Screen2;
    private javax.swing.JPanel Main_Screen;
    private javax.swing.JPanel Mathe_Screen4;
    private javax.swing.JPanel Programmieren_Screen1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton29;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton30;
    private javax.swing.JButton jButton31;
    private javax.swing.JButton jButton32;
    private javax.swing.JButton jButton33;
    private javax.swing.JButton jButton34;
    private javax.swing.JButton jButton35;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton52;
    private javax.swing.JButton jButton53;
    private javax.swing.JButton jButton54;
    private javax.swing.JButton jButton87;
    private javax.swing.JButton jButton88;
    private javax.swing.JButton jButton89;
    private javax.swing.JButton jButton90;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables
}
