/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package informel;

/**
 *
 * @author denisehfg
 */
public class Main extends javax.swing.JPanel {

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main_Screen = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        Programmieren_Screen = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        Basics_Screen = new javax.swing.JPanel();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        Mathe_Screen = new javax.swing.JPanel();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();
        jButton18 = new javax.swing.JButton();
        jButton19 = new javax.swing.JButton();
        Typo_Screen = new javax.swing.JPanel();
        jButton20 = new javax.swing.JButton();
        jButton21 = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();

        Main_Screen.setBackground(new java.awt.Color(255, 255, 255));
        Main_Screen.setForeground(new java.awt.Color(255, 255, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Circle_Info.png"))); // NOI18N
        jButton1.setToolTipText("");
        jButton1.setBorder(null);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Circle_Prog.png"))); // NOI18N
        jButton2.setBorder(null);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Circle_Typo.png"))); // NOI18N
        jButton4.setBorder(null);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Circle_Mathe.png"))); // NOI18N
        jButton3.setBorder(null);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Circle_Basics.png"))); // NOI18N
        jButton5.setBorder(null);

        javax.swing.GroupLayout Main_ScreenLayout = new javax.swing.GroupLayout(Main_Screen);
        Main_Screen.setLayout(Main_ScreenLayout);
        Main_ScreenLayout.setHorizontalGroup(
            Main_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_ScreenLayout.createSequentialGroup()
                .addContainerGap(274, Short.MAX_VALUE)
                .addGroup(Main_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Main_ScreenLayout.createSequentialGroup()
                        .addGroup(Main_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(Main_ScreenLayout.createSequentialGroup()
                                .addComponent(jButton4)
                                .addGap(154, 154, 154)
                                .addComponent(jButton5))
                            .addGroup(Main_ScreenLayout.createSequentialGroup()
                                .addComponent(jButton3)
                                .addGap(154, 154, 154)
                                .addComponent(jButton2)))
                        .addGap(160, 160, 160))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Main_ScreenLayout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(270, 270, 270))))
        );
        Main_ScreenLayout.setVerticalGroup(
            Main_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Main_ScreenLayout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(Main_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Main_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton4)
                    .addComponent(jButton5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Programmieren_Screen.setBackground(new java.awt.Color(255, 255, 255));
        Programmieren_Screen.setForeground(new java.awt.Color(255, 255, 255));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Circle_Prog.png"))); // NOI18N
        jButton10.setBorder(null);

        jButton11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Programmieren/Circle_Klassendef.png"))); // NOI18N
        jButton11.setBorder(null);

        jButton12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Programmieren/Circle_Array.png"))); // NOI18N
        jButton12.setBorder(null);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Programmieren/Circle_ObjundKla.png"))); // NOI18N
        jButton6.setBorder(null);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Programmieren/Circle_Schleifen.png"))); // NOI18N
        jButton7.setBorder(null);

        jButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Programmieren/Circle_if.png"))); // NOI18N
        jButton8.setBorder(null);

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Programmieren/Circle_Schleifen.png"))); // NOI18N
        jButton9.setBorder(null);

        javax.swing.GroupLayout Programmieren_ScreenLayout = new javax.swing.GroupLayout(Programmieren_Screen);
        Programmieren_Screen.setLayout(Programmieren_ScreenLayout);
        Programmieren_ScreenLayout.setHorizontalGroup(
            Programmieren_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Programmieren_ScreenLayout.createSequentialGroup()
                .addGroup(Programmieren_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Programmieren_ScreenLayout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(jButton6)
                        .addGap(18, 18, 18)
                        .addGroup(Programmieren_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10)
                            .addComponent(jButton8))
                        .addGap(30, 30, 30)
                        .addComponent(jButton9))
                    .addGroup(Programmieren_ScreenLayout.createSequentialGroup()
                        .addGap(234, 234, 234)
                        .addGroup(Programmieren_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Programmieren_ScreenLayout.createSequentialGroup()
                                .addComponent(jButton12)
                                .addGap(115, 115, 115)
                                .addComponent(jButton11)
                                .addGap(219, 219, 219)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        Programmieren_ScreenLayout.setVerticalGroup(
            Programmieren_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Programmieren_ScreenLayout.createSequentialGroup()
                .addGroup(Programmieren_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Programmieren_ScreenLayout.createSequentialGroup()
                        .addGroup(Programmieren_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Programmieren_ScreenLayout.createSequentialGroup()
                                .addGap(140, 140, 140)
                                .addComponent(jButton12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Programmieren_ScreenLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton11)))
                        .addGroup(Programmieren_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Programmieren_ScreenLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton10)
                                .addGap(29, 29, 29)
                                .addComponent(jButton8))
                            .addGroup(Programmieren_ScreenLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jButton6)))
                        .addGap(124, 124, 124))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Programmieren_ScreenLayout.createSequentialGroup()
                        .addComponent(jButton9)
                        .addGap(197, 197, 197)))
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Basics_Screen.setBackground(new java.awt.Color(255, 255, 255));
        Basics_Screen.setForeground(new java.awt.Color(255, 255, 255));

        jButton13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Circle_Basics.png"))); // NOI18N
        jButton13.setBorder(null);

        jButton14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Basics/Circle_Bruchrechnen.png"))); // NOI18N
        jButton14.setBorder(null);

        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Basics/Circle_Dreiecke.png"))); // NOI18N
        jButton15.setBorder(null);

        javax.swing.GroupLayout Basics_ScreenLayout = new javax.swing.GroupLayout(Basics_Screen);
        Basics_Screen.setLayout(Basics_ScreenLayout);
        Basics_ScreenLayout.setHorizontalGroup(
            Basics_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Basics_ScreenLayout.createSequentialGroup()
                .addContainerGap(254, Short.MAX_VALUE)
                .addGroup(Basics_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Basics_ScreenLayout.createSequentialGroup()
                        .addComponent(jButton15)
                        .addGap(115, 115, 115)
                        .addComponent(jButton14)
                        .addGap(219, 219, 219))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Basics_ScreenLayout.createSequentialGroup()
                        .addComponent(jButton13)
                        .addGap(325, 325, 325))))
        );
        Basics_ScreenLayout.setVerticalGroup(
            Basics_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Basics_ScreenLayout.createSequentialGroup()
                .addGroup(Basics_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Basics_ScreenLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButton15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Basics_ScreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton14)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton13)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        Mathe_Screen.setBackground(new java.awt.Color(255, 255, 255));
        Mathe_Screen.setForeground(new java.awt.Color(255, 255, 255));

        jButton16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Circle_Mathe.png"))); // NOI18N
        jButton16.setBorder(null);

        jButton17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Basics/Circle_Dreiecke.png"))); // NOI18N
        jButton17.setBorder(null);

        jButton18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Mathe/Circle_Komplexe.png"))); // NOI18N
        jButton18.setBorder(null);

        jButton19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Mathe/Circle_Grundbegriffe.png"))); // NOI18N
        jButton19.setBorder(null);

        javax.swing.GroupLayout Mathe_ScreenLayout = new javax.swing.GroupLayout(Mathe_Screen);
        Mathe_Screen.setLayout(Mathe_ScreenLayout);
        Mathe_ScreenLayout.setHorizontalGroup(
            Mathe_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Mathe_ScreenLayout.createSequentialGroup()
                .addContainerGap(254, Short.MAX_VALUE)
                .addGroup(Mathe_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Mathe_ScreenLayout.createSequentialGroup()
                        .addComponent(jButton16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton19))
                    .addGroup(Mathe_ScreenLayout.createSequentialGroup()
                        .addComponent(jButton18)
                        .addGap(115, 115, 115)
                        .addComponent(jButton17)))
                .addGap(219, 219, 219))
        );
        Mathe_ScreenLayout.setVerticalGroup(
            Mathe_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Mathe_ScreenLayout.createSequentialGroup()
                .addGroup(Mathe_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Mathe_ScreenLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButton18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Mathe_ScreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton17)))
                .addGroup(Mathe_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Mathe_ScreenLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton16)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Mathe_ScreenLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(jButton19)
                        .addGap(95, 95, 95))))
        );

        Typo_Screen.setBackground(new java.awt.Color(255, 255, 255));
        Typo_Screen.setForeground(new java.awt.Color(255, 255, 255));

        jButton20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Circle_Typo.png"))); // NOI18N
        jButton20.setBorder(null);

        jButton21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Basics/Circle_Dreiecke.png"))); // NOI18N
        jButton21.setBorder(null);

        jButton22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Mathe/Circle_Komplexe.png"))); // NOI18N
        jButton22.setBorder(null);

        jButton23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/informel/Images/Mathe/Circle_Grundbegriffe.png"))); // NOI18N
        jButton23.setBorder(null);

        javax.swing.GroupLayout Typo_ScreenLayout = new javax.swing.GroupLayout(Typo_Screen);
        Typo_Screen.setLayout(Typo_ScreenLayout);
        Typo_ScreenLayout.setHorizontalGroup(
            Typo_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Typo_ScreenLayout.createSequentialGroup()
                .addContainerGap(254, Short.MAX_VALUE)
                .addGroup(Typo_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(Typo_ScreenLayout.createSequentialGroup()
                        .addComponent(jButton20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton23))
                    .addGroup(Typo_ScreenLayout.createSequentialGroup()
                        .addComponent(jButton22)
                        .addGap(115, 115, 115)
                        .addComponent(jButton21)))
                .addGap(219, 219, 219))
        );
        Typo_ScreenLayout.setVerticalGroup(
            Typo_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Typo_ScreenLayout.createSequentialGroup()
                .addGroup(Typo_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Typo_ScreenLayout.createSequentialGroup()
                        .addGap(140, 140, 140)
                        .addComponent(jButton22))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Typo_ScreenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton21)))
                .addGroup(Typo_ScreenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Typo_ScreenLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton20)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Typo_ScreenLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                        .addComponent(jButton23)
                        .addGap(95, 95, 95))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Main_Screen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Programmieren_Screen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Basics_Screen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Mathe_Screen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Typo_Screen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Main_Screen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Programmieren_Screen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Basics_Screen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Mathe_Screen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Typo_Screen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
 /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_Test.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Basics_Screen;
    private javax.swing.JPanel Main_Screen;
    private javax.swing.JPanel Mathe_Screen;
    private javax.swing.JPanel Programmieren_Screen;
    private javax.swing.JPanel Typo_Screen;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private javax.swing.JButton jButton18;
    private javax.swing.JButton jButton19;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton20;
    private javax.swing.JButton jButton21;
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    // End of variables declaration//GEN-END:variables
}
